### ISSUE TITLE
GithubのIssueを自動でcloseする仕組みについて検討する

### ISSUE THREAD

**Issue by morieeeenyo** [morieeeenyo/django-chat-gpt-app#11]
# やりたいこと
みた感じ、Project上でDoneになったからといってcloseされない
が逆はできる
ので自動でcloseする仕組みを導入することで、楽になりたい

```yml
name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          stale-issue-label: "stale"
          exempt-issue-labels: 'bug,enhancement'
          days-before-issue-stale: 60
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
```
こんな感じのGithub Actionsが使えるかも
